apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-product-app-blue
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-product-app
      version: blue
  template:
    metadata:
      labels:
        app: enterprise-product-app
        version: blue
    spec:
      containers:
        - name: enterprise-product-app
          image: 484826611947.dkr.ecr.us-east-1.amazonaws.com/enterprise-product-app:28
          ports:
            - containerPort: 8080