apiVersion: v1
kind: Service
metadata:
  name: enterprise-product-bluegreen-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: enterprise-product-app
    version: blue
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30084