pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO = '484826611947.dkr.ecr.us-east-1.amazonaws.com/enterprise-product-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'app/target/*.jar'
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                docker build \
                -t enterprise-product-app:${IMAGE_TAG} \
                -f product-docker/Dockerfile .
                '''
            }
        }

        stage('ECR Login') {
            steps {
                sh '''
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS \
                --password-stdin ${ECR_REPO}
                '''
            }
        }

        stage('Push To ECR') {
            steps {
                sh '''
                docker tag enterprise-product-app:${IMAGE_TAG} \
                ${ECR_REPO}:${IMAGE_TAG}

                docker push ${ECR_REPO}:${IMAGE_TAG}
                '''
            }
        }
    }
}