apiVersion: v1
kind: Service
metadata:
  name: enterprise-product-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: enterprise-product-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: ${NODE_PORT}